### ISSUE TITLE
Issues with snoopy and keepalived

### ISSUE THREAD

**Issue by kippi6171** [a2o/snoopy#100]
All

We have deployed snoopy to our development environment however we have the following configuration in keepalived:

vrrp_script chk_haproxy {                       # Requires keepalived-1.1.13
    script /root/scripts/chk_haproxy.sh
    interval 2                                  # check every 2 seconds
}

Since installing snoopy this seems to fail and cause keepalived to flip. 

Nov 16 08:27:22 HOSTNAME Keepalived_vrrp[5139]: VRRP_Script(chk_haproxy) timed out
Nov 16 08:27:22 HOSTNAME Keepalived_vrrp[5139]: Process [6810] didn't respond to SIGTERM

The script is doing:

killall -0 haproxy

Any suggestions are welcome.

Thanks

Chris

**Comment by bostjan** [comment]
Too many variables here:
- snoopy version
- snoopy configuration (logs via syslog or directly to file?)

I am using keepalived with snoopy for couple of years now, no problems.

**Comment by kippi6171** [comment]
Snoopy version is: 2.4.7
Logging to a directory

Thanks

Chris.

**Comment by bostjan** [comment]
I guess logging is hanging on a syscall to write to file, or something similar. Can you provide strace and lsof outputs for relevant processes (either bash or killall, maybe something else)?

You will probably notice that one of these processes is stuck at some syscall or sth. Does using devlog output provider work?

b.

**Comment by kippi6171** [comment]
Let me write a check that keeps calling killall, as when I have been testing by hand it never fails.

The devlog is available but not using it at the moment.

Thanks

Chris

**Comment by bostjan** [comment]
Also test with similarly-configured environment, and under same user.

b.

**Comment by kippi6171** [comment]
We have about 20 dev environments that are all the same, what it looks like is the split second that snoopy is adding is taking the whole process over 1 second.

This isn't a fault of snoopy but that killall is expensive and clearly adding another layer however small is causing the process to slow down just enough to trip keepalived.

Thanks for all your help.

Chris.

**Comment by bostjan** [comment]
Tnx for reporting back the cause of your problems.

b.
