### ISSUE TITLE
configuration with LOG_LOCAL[0-7] does not work

### ISSUE THREAD

**Issue by lhmerino** [a2o/snoopy#102]
## Issue description - Environment basics

(replace 'FILLIN' with actual values from your environment)

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | x86 is not supported anymore     |
| Linux distribution:                 | Ubuntu            | |
| Distribution version:               | 14.04            | |
| Snoopy version:                     | Latest            | |
| Snoopy config file was used:        | no   | snoopy-install.sh enables this by default |
| Snoopy threading support enabled:   | no   | not enabled by default as of v2.4.4       |

## Issue description - How was Snoopy installed

Downloading from script

git clone https://github.com/a2o/snoopy.git
cd snoopy
git submodule init
git submodule update

# This generates ./configure script
./bootstrap.sh
OUTPUT:
## Issue description - Describe the problem you are having

Cannot configure with option --with-syslog-facility=LOG_LOCAL7

./configure --with-syslog-facility=LOG_LOCAL7

any --with-sylog-facility=LOG_LOCAL[0-7] does not work

## Expected result

A successful configuration - no error

## Actual result

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gawk... (cached) gawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for grep that handles long lines and -e... (cached) /bin/grep
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... (cached) ranlib
checking for a sed that does not truncate output... (cached) /bin/sed
checking for dirname... yes
checking for readlink... yes
checking for socat... yes
checking for wc... yes
checking for dlsym in -ldl... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for dlfcn.h... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking features.h usability... yes
checking features.h presence... yes
checking for features.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking sys/syscall.h usability... yes
checking sys/syscall.h presence... yes
checking for sys/syscall.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/types.h... (cached) yes
checking sys/un.h usability... yes
checking sys/un.h presence... yes
checking for sys/un.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking for inline... inline
checking for pid_t... yes
checking for size_t... yes
checking for uid_t in sys/types.h... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for getcwd... yes
checking for gethostname... yes
checking for getsid... yes
checking for gettimeofday... yes
checking for socket... yes
checking for strchr... yes
checking for strdup... yes
checking for strstr... yes
configure: ======================================================================
configure: Snoopy all features enabled/disabled: no - using defaults
configure: -
configure: Snoopy config file enabled:   yes
configure: Snoopy config file path:      /usr/local/etc/snoopy.ini
configure: Snoopy error logging enabled: no
configure: Snoopy thread safety enabled: no
configure: -
configure: Snoopy datasource enabled: cmdline ............... YES
configure: Snoopy datasource enabled: cwd ................... YES
configure: Snoopy datasource enabled: datetime .............. YES
configure: Snoopy datasource enabled: domain ................ YES
configure: Snoopy datasource enabled: egid .................. YES
configure: Snoopy datasource enabled: egroup ................ YES
configure: Snoopy datasource enabled: env ................... YES
configure: Snoopy datasource enabled: env_all ............... YES
configure: Snoopy datasource enabled: euid .................. YES
configure: Snoopy datasource enabled: eusername ............. YES
configure: Snoopy datasource enabled: filename .............. YES
configure: Snoopy datasource enabled: gid ................... YES
configure: Snoopy datasource enabled: group ................. YES
configure: Snoopy datasource enabled: hostname .............. YES
configure: Snoopy datasource enabled: login ................. YES
configure: Snoopy datasource enabled: pid ................... YES
configure: Snoopy datasource enabled: ppid .................. YES
configure: Snoopy datasource enabled: rpname ................ YES
configure: Snoopy datasource enabled: sid ................... YES
configure: Snoopy datasource enabled: snoopy_literal ........ YES
configure: Snoopy datasource enabled: snoopy_threads ........ YES
configure: Snoopy datasource enabled: snoopy_version ........ YES (forced)
configure: Snoopy datasource enabled: tid ................... YES
configure: Snoopy datasource enabled: tid_kernel ............ YES
configure: Snoopy datasource enabled: timestamp ............. YES
configure: Snoopy datasource enabled: timestamp_ms .......... YES
configure: Snoopy datasource enabled: timestamp_us .......... YES
configure: Snoopy datasource enabled: tty ................... YES
configure: Snoopy datasource enabled: tty_uid ............... YES
configure: Snoopy datasource enabled: tty_username .......... YES
configure: Snoopy datasource enabled: uid ................... YES
configure: Snoopy datasource enabled: username .............. YES
configure: Snoopy default message format: "[uid:%{uid} sid:%{sid} tty:%{tty} cwd:%{cwd} filename:%{filename}]: %{cmdline}"
configure: -
configure: Snoopy filtering subsystem enabled: yes
configure: Snoopy filter enabled: exclude_spawns_of ......... YES
configure: Snoopy filter enabled: exclude_uid ............... YES
configure: Snoopy filter enabled: only_root ................. YES
configure: Snoopy filter enabled: only_tty .................. YES
configure: Snoopy filter enabled: only_uid .................. YES
configure: Snoopy default filter chain: (none)
configure: -
configure: Snoopy output enabled: devlog .................... YES
configure: Snoopy output enabled: devnull ................... YES
configure: Snoopy output enabled: devtty .................... YES
configure: Snoopy output enabled: file ...................... YES (forced)
configure: Snoopy output enabled: socket .................... YES (forced)
configure: Snoopy output enabled: stderr .................... YES
configure: Snoopy output enabled: stdout .................... YES
configure: Snoopy output enabled: syslog .................... no
configure: Snoopy default output:          default (system dependent)
configure: Snoopy default output argument: (none)
configure: -
configure: error: --with-syslog-facility value provided is invalid: LOG_LOCAL7

## Steps to reproduce

git clone https://github.com/a2o/snoopy.git
cd snoopy
git submodule init
git submodule update
./bootstrap.sh
./configure --with-syslog-facility=LOG_LOCAL7

**Comment by bostjan** [comment]
Thanks for report (I like the new issue template feature of GitHub, you are the first to use it:)

Can you try the fix I have pushed to this branch and report back the results?
https://github.com/a2o/snoopy/tree/bugfix/github-102-syslog-facility-localX

Tnx,
b.

**Comment by lhmerino** [comment]
The issue template is really nice! It made it easy for me to know what to include.

I just tried the modified version of configure.ac and it works with no problems. Thanks!

**Comment by bostjan** [comment]
Released 2.4.5 in response to this.

I've figured I missed this section of code with build test suite (only the enable/disable flags were taken into account).

Tnx for taking time to confirm the bugfix.

b.
