### ISSUE TITLE
Install Snoopy on Freebsd

### ISSUE THREAD

**Issue by berzia** [a2o/snoopy#105]
Hi,
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [x] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [x] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [x] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue
## Issue description - Environment basics

(replace 'FILLIN' with actual values from your environment)

| Key | Value | Comments |
| --- | --- | --- |
| Architecture: | x86_64 | x86 is not supported anymore |
| Linux distribution: | Freebsd |  |
| Distribution version: | 10.2-RELEASE-p16 |  |
| Snoopy version: | 2.4.5 |  |
| Snoopy config file was used: | FILLIN (yes/no) | snoopy-install.sh enables this by default |
| Snoopy threading support enabled: | FILLIN (yes/no) | not enabled by default as of v2.4.4 |
## Issue description - How was Snoopy installed

git clone https://github.com/a2o/snoopy.git
cd snoopy
git submodule init
git submodule update
./bootstrap.sh

(describe installation method - snoopy-install.sh, custom built (provide configure arguments), distro package)
## Issue description - Describe the problem you are having

When I try to install snoopy with _./configure_ , snoopy returns this : 

```
checking for dlsym in -ldl... no
configure: error: A library is missing. Unable to continue.
```

Can you help me please ?

Bye

**Comment by bostjan** [comment]
I see this is not documented anywhere, but Snoopy is pretty much linux-oriented ATM, or better, untested on other unix platforms.

There was some work being done for OS X, but is far from complete.

What can I say - patches welcome! :)
