### ISSUE TITLE
$LIB variable in /etc/ld.so.preload does not enable multilib support in Unbutu 16.04

### ISSUE THREAD

**Issue by mpw6** [a2o/snoopy#112]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [X] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [X] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [X] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

(replace 'FILLIN' with actual values from your environment)

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | x86 is not supported anymore     |
| Linux distribution:                 | Ubuntu            | |
| Distribution version:               | 16.04            | |
| Snoopy version:                     | 2.4.6            | |
| Snoopy config file was used:        | yes   | snoopy-install.sh enables this by default |
| Snoopy threading support enabled:   | no   | not enabled by default as of v2.4.4       |

## Issue description - How was Snoopy installed

Original install with preferred method: 

```
rm -f snoopy-install.sh &&
wget -q -O snoopy-install.sh https://github.com/a2o/snoopy/raw/install/doc/install/bin/snoopy-install.sh &&
chmod 755 snoopy-install.sh &&
./snoopy-install.sh stable
```

To compile a 32-bit version the following sequence was followed:

```
apt-get install gcc-multilib
mkdir /usr/local/lib64
cp -p /usr/local/lib/libsnoopy.* /usr/local/lib64
rm -rf snoopy-2.4.6
tar xfz snoopy-2.4.6.tar.gz
cd snoopy-2.4.6
CFLAGS=-m32 ./configure
make
make install
make enable
vi /etc/ld.so.preload
    /usr/local/$LIB/libsnoopy.so
reboot
```

## Issue description - Describe the problem you are having

Once multilib has been enabled as shown above, every command run gets the following error:

> 
ERROR: ld.so: object '/usr/local/$LIB/libsnoopy.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

**Comment by bostjan** [comment]
Hey Mike,

It would seem that $LIB is not supported by `ld` anymore.
Does it work if you do not use absolute path, but just `libsnoopy.so`?

Please refer to this page, where this approach is described (for another software):
https://github.com/rizsotto/Bear/issues/134

We might need to make installation step distro/version-dependent (yuck).
This has not been tested, nor will be on my end. If you do research the topic and come up with a solution, pull requests are always welcome.

**Comment by mpw6** [comment]
Boštjan,

Thank you for looking into this. I'm not sure why I didn't try this variation. At first, I saw this:
`ERROR: ld.so: object 'libsnoopy.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.`
Then I made sure that both `/usr/local/lib` and `/usr/local/lib64` were included in my `LD_LIBRARY_PATH`. That seems to have fixed it for 32-bit programs, but not for 64-bit. I no longer see any errors, but 64-bit programs do not get logged.

With respect to the [rizsotto/Bear#134](https://github.com/rizsotto/Bear/issues/134) approach, I should mention that I had left out an important piece of information above.
`apt-get install gcc-multilib` prior to `CFLAGS=-m32 ./configure`.  I'll edit the original post to include it.

Mike

**Comment by mpw6** [comment]
Update: I missed something the first time.  I tried this, and it seems to work:

copy 32-bit library to /usr/lib/i386-linux-gnu/ then copy 64-bit library to /usr/lib/x86_64-linux-gnu/.

I'm not yet certain that everything is getting logged, but I will test and let you know.

**Comment by mpw6** [comment]
Ok, this does seem to work:

```
su -
rm -f snoopy-install.sh &&
wget -q -O snoopy-install.sh https://github.com/a2o/snoopy/raw/install/doc/install/bin/snoopy-install.sh &&
chmod 755 snoopy-install.sh &&
./snoopy-install.sh stable
reboot
```
```
su -
mv /usr/local/lib/libsnoopy.* /usr/lib/x86_64-linux-gnu/
apt-get install gcc-multilib
rm -rf snoopy-2.4.6
tar xfz snoopy-2.4.6.tar.gz
cd snoopy-2.4.6
CFLAGS=-m32 ./configure
make
make install
mv /usr/local/lib/libsnoopy.* /usr/lib/i386-linux-gnu/
echo 'libsnoopy.so' > /etc/ld.so.preload
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib
```

**Comment by bostjan** [comment]
Thanks for following up with a solution!

**Comment by Gerardwx** [comment]
On my Ubuntu 16.04 system, I ended up doing:

> wget -q -O snoopy-install.sh https://github.com/a2o/snoopy/raw/install/doc/install/bin/snoopy-install.sh && chmod 755 snoopy-install.sh && ./snoopy-install.sh stable
reboot

and then

> mv /usr/local/lib/libsnoopy.* /usr/lib/x86_64-linux-gnu/
apt-get install gcc-multilib
./snoopy_install.sh download
rm -rf snoopy-2.4.6
tar xfz snoopy-2.4.6.tar.gz
cd snoopy-2.4.6
CFLAGS=-m32 ./configure
make
make install 
mv /usr/local/lib/libsnoopy.* /usr/lib/i386-linux-gnu/
echo 'libsnoopy.so' > /etc/ld.so.preload
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib

While this logs 32-bit and 64-bit programs, when certain commands are executed, we get an error message about being unable to load the shared library. e.g.

> $ sudo ls file
ERROR: ld.so: object 'libsnoopy.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
file

Has anyone else found this?

**Comment by vincentroberge** [comment]
I am working on Ubuntu 20.04 and I have tried to replicated the solution proposed by mpw6 to be able to monitor 32 bits and 64 bits applications. My system is configured with the 32 bits and 64 bits toolchain. Under /usr, I have /usr/lib and /usr/lib32. Under /usr/local/, I have /usr/local/lib. I tried different combination of where to copy the libsnoopy.* files, but nothing works. I am not able to load the 32-bit library dynamically. Any help would be greatly appreciated. Thank you.

**Comment by bostjan** [comment]
@vincentroberge, two things:
- @mpw6's method works (I've just tested it on Ubuntu 20.04 64bit, with 32-bit zsh installed, and snoopy logged everything)
- multiarch support is really low on a priority list - anybody dabbling with multiarch should be proficient enough to be able to resolve such issues.

That said, let me try to clean up the installation guide a bit, in hopes to get things clarified (verified on Ubuntu 20.04, not sure if this will work on other distributions too).

Before we start, let's install the build prerequisites:
```
apt-get update
apt-get install gcc gzip make procps socat tar wget   # Standard prerequisites
apt-get install gcc-multilib   # For 32-bit builds
```

First, download and unpack the sources:
```
wget https://github.com/a2o/snoopy/releases/download/snoopy-2.4.15/snoopy-2.4.15.tar.gz &&
tar -xzf snoopy-2.4.15.tar.gz &&
cd snoopy-2.4.15
```

Then let's build the 64-bit version first (we're using the same configure flags as `install-snoopy.sh`):
```
make distclean &&
./configure --enable-config-file --sysconfdir=/etc --enable-filtering --libdir=/usr/lib/x86_64-linux-gnu &&
make &&
make install
```

Now let's build and install the 32-bit variation too (notice the different `--libdir` flag + added `CFLAGS=-m32` environmental variable for the `./configure` command. Also, if `make distclean` step fails with `make: *** No rule to make target 'distclean'.  Stop.` error, that means it has already run):
```
make distclean &&
CFLAGS=-m32 ./configure --enable-config-file --sysconfdir=/etc --enable-filtering --libdir=/usr/lib/i386-linux-gnu &&
make &&
make install
```

At last, let's enable the Snoopy preloading as @mpw6 described:
```
echo 'libsnoopy.so' > /etc/ld.so.preload
```
All done. Potentially you'll need to reboot your system, or just start another shell session to see the effects.


**Testing**
Personally, I've tested the functionality of the above by installing 32-bit `zsh` next to existing 64-bit bash on my 64-bit Ubuntu 20.04, like this:
```
# Install 32-bit zsh:
dpkg --add-architecture i386
apt-get update
apt-get install zsh:i386

# Get into the 32-bit zsh:
zsh

# Now let's run a unique command to see if 32-bit logging works:
tail -f /var/log/auth.log -n14
```

And sure enough, in the output of the last command, the expected `-n14` appeared (in the very last line, as expected):
```
t-snoopy-2004-multilib# tail -f /var/log/auth.log -n14
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14408]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/bin/chown]: chown --reference=/etc/shells /etc/shells.tmp
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14409]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/bin/mv]: mv /etc/shells.tmp /etc/shells
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14410]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/bin/ln]: ln -s /bin/zsh /usr/bin/zsh
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14411]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/usr/bin/dpkg-maintscript-helper]: dpkg-maintscript-helper symlink_to_dir /usr/share/doc/zsh zsh-common 5.0.7-3 -- configure
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14412]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/usr/bin/basename]: basename /usr/bin/dpkg-maintscript-helper
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14413]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/usr/bin/dpkg]: dpkg --validate-version -- 5.0.7-3
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14415]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/sbin/ldconfig]: ldconfig
Nov 26 19:40:35 t-snoopy-2004-multilib snoopy[14415]: [uid:0 sid:14352 tty:/dev/pts/5 cwd:/ filename:/sbin/ldconfig.real]: /sbin/ldconfig.real
Nov 26 19:40:36 t-snoopy-2004-multilib snoopy[14421]: [uid:0 sid:278 tty:/dev/pts/4 cwd:/tmp filename:/usr/lib/ubuntu-advantage/apt-esm-hook]: /usr/lib/ubuntu-advantage/apt-esm-hook post-invoke-success
Nov 26 19:40:42 t-snoopy-2004-multilib snoopy[14422]: [uid:0 sid:278 tty:/dev/pts/4 cwd:/snoopy-2.4.15 filename:/usr/bin/zsh]: zsh
Nov 26 19:40:42 t-snoopy-2004-multilib snoopy[14423]: [uid:0 sid:278 tty:/dev/pts/4 cwd:/snoopy-2.4.15 filename:/usr/bin/getent]: getent group root
Nov 26 19:40:42 t-snoopy-2004-multilib snoopy[14442]: [uid:0 sid:278 tty:/dev/pts/4 cwd:/snoopy-2.4.15 filename:/bin/mv]: mv -f /root/.zcompdump.t-snoopy-2004-multilib.14422 /root/.zcompdump
Nov 26 19:40:57 t-snoopy-2004-multilib snoopy[14445]: [uid:0 sid:278 tty:(none) cwd:/snoopy-2.4.15 filename:/usr/bin/tail]: tail --version
Nov 26 19:41:09 t-snoopy-2004-multilib snoopy[14446]: [uid:0 sid:278 tty:/dev/pts/4 cwd:/snoopy-2.4.15 filename:/usr/bin/tail]: tail -f /var/log/auth.log -n14
^C
t-snoopy-2004-multilib# 
```

@vincentroberge, if this^ does not help you solve your particular issue, you'll probably need to pay someone to have a look at your particular system and figure out what's going on.

**Comment by vincentroberge** [comment]
@bostjan Thank you so much. This is a very complete guide. I just tried it and it works very well.
