### ISSUE TITLE
installation done and reboot machine,but no any record information in /var/log/*

### ISSUE THREAD

**Issue by Togal** [a2o/snoopy#127]
## Checklist before I submit this issue report

I confirm that:
- [ ] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [ ] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [ ] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [ ] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

(replace 'FILLIN' with actual values from your environment)

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | x86 is not supported anymore     |
| Linux distribution:                 | RedHat            | |
| Distribution version:               | 6.9            | |
| Snoopy version:                     | stable            | |
| Snoopy config file was used:        | no   | snoopy-install.sh enables this by default |
| Snoopy threading support enabled:   | no  | not enabled by default as of v2.4.4       |

## Issue description - How was Snoopy installed

FILLIN
(describe installation method - snoopy-install.sh, custom built (provide configure arguments), distro package)

## Issue description - Describe the problem you are having

installation  and reboot machine,but no any record information in /var/log/*
## Actual result
![image](https://user-images.githubusercontent.com/9533360/34648642-3beb29f4-f3d8-11e7-9c3a-6c6a9d7dbbf0.png)

## Steps to reproduce

FILLIN

**Comment by bostjan** [comment]
Is your syslog daemon working?
