### ISSUE TITLE
Command output logging

### ISSUE THREAD

**Issue by c3c** [a2o/snoopy#128]
I confirm that:
- [ ] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [x] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [x] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [x] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

I'm looking for a logging solution that can also log the output of the executed commands. Does snoopy support this?

**Comment by bostjan** [comment]
Short answer: no.

Longer version:
Snoopy inserts itself between the current and the start of the next process and is thus capable of logging the process startup parameters (command, pwd etc.). As soon as it is done doing what it is designed to do, it does not interfere with the new process anymore at all, unless that new process executes another program.
