### ISSUE TITLE
snoopy crashes GitLab

### ISSUE THREAD

**Issue by m-osmani** [a2o/snoopy#129]
## Issue description - Environment basics

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | x86 is not supported anymore     |
| Linux distribution:                 | Debian            | | jessie
| Distribution version:               | 8.9             | | 
| Snoopy version:                     | 1.8.0-5            | |
| Snoopy config file was used:        | no    | snoopy-install.sh enables this by default |
| Snoopy threading support enabled:   | no  | not enabled by default as of v2.4.4       |

## Issue description - How was Snoopy installed

apt-get install snoopy

## Issue description - Describe the problem you are having

Please review the issue https://gitlab.com/gitlab-org/gitlab-ce/issues/25800

It is really important.

If snoopy is active on the server then redis gets information which does not belongs to it.

The results are dead jobs and 500 errors.

## Expected result

successful running jobs

## Steps to reproduce

Install gitlab 
Install snoopy
Run gitlab
Open admin-page of gitlab and make multiple force refresh.

**Comment by bostjan** [comment]
1.8.x is ancient version of Snoopy. Closing.

Retest with latest version and if the issue persist, reopen this issue (or open a new one).

**Comment by bostjan** [comment]
"It is really important." <--- what do you mean by that?
