### ISSUE TITLE
Piped echo commands in bash don´t get logged

### ISSUE THREAD

**Issue by ifmusic** [a2o/snoopy#132]
## Issue description - Environment basics

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | |
| Linux distribution:                 | Ubuntu 16LTS            | |
| Distribution version:               | 16.04 LTS            | |
| Snoopy version:                     | 2.4.6            | |
| Snoopy config file was used:        | no   | |
| Snoopy threading support enabled:   | default   | |

## Issue description - How was Snoopy installed
        - snoopy-install.sh

## Issue description - Describe the problem you are having
Snoopy logs great but I can´t see these kinds of commands being logged:
`echo test123 > newfile.txt`

(Evertything else looks normal)

## Expected result
I thought that echo command should have generated an execve and, therefore, an entry log in snoppy.

## Actual result
No output log

## Steps to reproduce
Vanilla install via script, run that echo or similar

Thanks!

**Comment by bostjan** [comment]
"echo" is a bash internal command. Use `/bin/echo` to execute the external echo binary.
