### ISSUE TITLE
CoreOS or Docker support

### ISSUE THREAD

**Issue by mrsanuk** [a2o/snoopy#138]
Have you ever tried run snoopy on CoreOS or in Docker container?

**Comment by dAnjou** [comment]
@rdlmda, this is most likely caused by #158. A workaround is to install from a Git ref: https://github.com/a2o/snoopy/blob/360bb18e16ceaca16a22b94be9e17fd5f2184c01/doc/install/bin/snoopy-install.sh#L29 which just worked for me.

**Comment by bostjan** [comment]
Most likely a duplicate of #146, just as @dAnjou suggested. Closing now, do reopen it if the issue still persists.
