### ISSUE TITLE
Snoopy causing tmux to hang

### ISSUE THREAD

**Issue by eugk** [a2o/snoopy#141]
## Checklist before I submit this issue report

I confirm that:
- [ X ] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [ X ] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [ X ] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [ X ] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | |
| Linux distribution:                 | CentOS            | |
| Distribution version:               | 6.7            | |
| Snoopy version:                     | 2.4.6            | |
| Snoopy config file was used:        | no   | but custom config was compiled in |
| Snoopy threading support enabled:   | no   | |

Built from source and configured as such:

`--disable-config-file --with-message-format="user=%{login} uid=%{tty_uid} e_user=%{eusername} e_uid=%{euid} sid=%{sid} tty=%{tty} cwd=%{cwd} file=%{filename} cmd=%{cmdline}" --with-syslog-facility=LOCAL2 --with-syslog-level=INFO --with-default-output=syslog --enable-output-syslog --with-filter-chain="only_tty;exclude_spawns_of:cron"`

## Issue description

When snoopy is enabled, tmux hangs on launch. I can run tmux, and it comes up, but it hangs before the bash prompt appears. If I hit control-C the prompt does appear, but it hangs again if I run any other command. Based on strace output, it's stuck on stat("/etc/localtime"), which eventually times out, and then is retried continuously. Attached strace output at the bottom.

Any troubleshooting tips (or fixes) would be appreciated. Thanks!

```
[root@hn109:~]# ps aux|grep tmux
eugene   16867  0.0  0.0 120680  1444 pts/0    S+   13:07   0:00 tmux
eugene   16869  0.0  0.0 122964  1744 ?        Ss   13:07   0:00 tmux
root     16877  0.0  0.0 109632  1036 pts/1    S+   13:07   0:00 grep tmux
[root@hn109:~]# strace -p 16869
Process 16869 attached
restart_syscall(<... resuming interrupted call ...>) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN|POLLOUT}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 14965) = 1 ([{fd=5, revents=POLLOUT}])
writev(5, [{"\33[?25l\33[60d\33[30m\33[42m[0] 0:bash*"..., 205}], 1) = 205
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 14965

) = 0 (Timeout)
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 20) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 15000) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 15000) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 15000) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN|POLLOUT}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 14935) = 1 ([{fd=5, revents=POLLOUT}])
writev(5, [{"\33[?25l\33[60d\33[30m\33[42m[0] 0:bash*"..., 205}], 1) = 205
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 14935) = 0 (Timeout)
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 51) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 15000) = 0 (Timeout)
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2819, ...}) = 0
poll([{fd=4, events=POLLIN}, {fd=6, events=POLLIN}, {fd=5, events=POLLIN}, {fd=8, events=POLLIN}, {fd=7, events=POLLIN}], 5, 15000
Process 16869 detached
 <detached ...>
```

**Comment by bostjan** [comment]
@eugk, seems to be working for me (tmux in CentOS 6.x LXC container, with latest Snoopy from git installed as specified).

![image](https://user-images.githubusercontent.com/107080/49295865-1303aa80-f4b7-11e8-95ec-5d9b94c7521c.png)

Do you have any .bash_profile/.bashrc files that do odd things?
If so, can you try removing those and see if it fixes the issue?

**Comment by eugk** [comment]
Interesting. It works if I run tmux-2.8, but hangs on tmux-2.3. I don't know what the interaction is with snoopy that's breaking the older tmux version, but I should be able to move people to the new one.

**Comment by bostjan** [comment]
How did you install the 2.3 version? I installed "mine" from EPEL, which apparently installs v1.6-3.

**Comment by eugk** [comment]
I am not sure how or why we have these versions installed. It's from an internal image that someone else updated. So far I haven't heard any complaints about tmux-2.8, so I don't plan to further investigate the issue with the older version.

**Comment by bostjan** [comment]
Alright. If somebody spots something similar somewhere else (but in the latest version), we'll revise it then. Thanks for the report anyway.

**Comment by eugk** [comment]
Interesting development here. It seems that the version of tmux doesn't matter. Instead, the name of the tmux binary being run is causing it to lock up. If I run `tmux-2.8`, it works fine. If I run a copy of that same binary called `tmux`, it freezes in the way I described above. This is very strange and only happens on CentOS 6 systems where we have snoopy installed. If anyone has any ideas, please let me know!
