### ISSUE TITLE
Compiler error on strncpy0 (or GCC 8.x in general)

### ISSUE THREAD

**Issue by PaulCombal** [a2o/snoopy#142]
I can't seem to be able to compile on Manjaro linux :(

I used the command from the README to install, but had to sudo for some reason. 

`gcc version 8.2.1 20181127 (GCC)
`
```
In function 'strncpy0',
    inlined from 'ini_parse_stream' at ini.c:164:17:
ini.c:67:5: error: 'strncpy' specified bound 50 equals destination size [-Werror=stringop-truncation]
     strncpy(dest, src, size);
     ^~~~~~~~~~~~~~~~~~~~~~~~
In function 'strncpy0',
    inlined from 'ini_parse_stream' at ini.c:130:17:
ini.c:67:5: error: 'strncpy' specified bound 50 equals destination size [-Werror=stringop-truncation]
     strncpy(dest, src, size);
     ^~~~~~~~~~~~~~~~~~~~~~~~
```

Can you reproduce the error, or did I do something wrong?

**Comment by bostjan** [comment]
Hey @PaulCombal, thanks for reporting this.

It looks like GCC 8.x has added additional checks and Snoopy is using `-Wall -Werror`, hence this issue got "pointed out".

Three things seems to be needed to get it fixed:
- Upgrade inih library
- Two minor fixes in the Snoopy itself

The PR #143 should fix this - can you test it out and confirm that this PR fixes the issue for you?

**Comment by PaulCombal** [comment]
Hello @bostjan ,

Yeah, I have the same error when trying to `make` from a master clone, I tried building from PR #143 andd it worked sucessfully.

Thank you!

**Comment by bostjan** [comment]
Fix released in https://github.com/a2o/snoopy/releases/tag/snoopy-2.4.7.
