### ISSUE TITLE
exclude_spawns_of not working for main process inside the docker container

### ISSUE THREAD

**Issue by alex-ren** [a2o/snoopy#145]
## Checklist before I submit this issue report

I confirm that:
- [x ] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [x ] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [x ] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [x ] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | |
| Linux distribution:                 | debian:stretch-slim            | |
| Distribution version:               | debian:stretch-slim            | |
| Snoopy version:                     | 360bb18e16ceaca16a22b94be9e17fd5f2184c01            | |
| Snoopy config file was used:        | Yes  | |
| Snoopy threading support enabled:   | No idea. I didn't change anything related to threading  | |

## Issue description - How was Snoopy installed
I installed the snoopy inside a docker container. (Please refer to https://github.com/alex-ren/snoopy-docker for the Dockerfile and other auxiliary files) The snoopy version installed is the newest commit from github.

## Issue description - Describe the problem you are having

I use `filter_chain = "exclude_spawns_of:python"` in the snoopy.ini.

I run the container with python as the main process, the executables launched by the python program are logged in /var/log/snoopy/snoopy.log. On the other hand, we I use "docker exec" to get into the running container and run another python program, the executables launched by that python program are not logged in /var/log/snoopy/snoopy.log.

## Steps to reproduce
1. Build the docker image
`docker build -t snoopy-docker .`
2. Run the docker container
`docker run --name snoopy-docker --rm snoopy-docker`
3. Use
`docker exec -it snoopy-docker /bin/bash`
to get into the container and check the file /var/log/snoopy/snoopy.log .

## Expected result

No executables launched by any python program shall be logged by snoopy.

Could this be an issue related to the combination of docker technique and the mechanism snoopy relies on for logging, or just a bug of the exclude_spawns_of filter? Thanks.

**Comment by bostjan** [comment]
Hey @alex-ren, this looks like a consequence of how Snoopy works:
- When the process is started, the libsnoopy.so is preloaded, and it overloads the `execv`/`execve` system calls with a function that first logs what's about to happen, and then executes the system call.
- In your particular case, when you execute `docker exec -it snoopy-docker /bin/bash`, the `bash` is such process - to log that, you'd need to have bash's parent process with the overloaded `exec`, which is not the case here.
- Anything that is executed with that `bash` is logged as usual.

This is the consequence of Docker's `exec` implementation, where the executed `bash` is not a subchild of your main.py python process, but an entirely separate process that is just "constructed" (actually, namespaced) in the same way as your container and thus appears to be running within the same context (and it is, for all intents and purposes, once it is finally running).

This situation probably deservers an entry in Snoopy's FAQ.

**Comment by bostjan** [comment]
@alex-ren, now I see what you mean now. Thank you for the extra effort in making the reproduction of the issue as simple as possible.

That said, on my end, at least I see a consistent failure - both `python` processes, the main one (started via `docker run`) and the auxiliary one (started via `docker exec -it /bin/bash` and running `python `test01.py` from there), are producing entries in `/var/log/snoopy/snoopy.log`.

**Comment by bostjan** [comment]
@alex-ren, the fix is merged and will be released in the upcoming 2.4.10 release.

Thanks for reporting the issue and thanks for making it simple to reproduce, that docker image is just awesome. ;)

**Comment by alex-ren** [comment]
@bostjan thank you so much for following up with this. Much appreciated. Let me try the new version.
