### ISSUE TITLE
source.a2o.si is down breaking the installer

### ISSUE THREAD

**Issue by edaily** [a2o/snoopy#146]
As said in the title, http://source.a2o.si/download/snoopy seems to be down which is preventing the install script from completing.

**Comment by gnalawade** [comment]
Meanwhile workaround is to try with specific version which is latest stable 
./snoopy-install.sh git-snoopy-2.4.6

**Comment by jualbacar** [comment]
trying ./snoopy-install.sh git-snoopy-2.4.6 I get this error, did in an Amazon Linux 2:
Making all in datasource
make[3]: se ingresa al directorio `/root/snoopy-install-from.git/src/datasource'
  CC       noop.lo
  CC       cmdline.lo
cmdline.c: In function 'snoopy_datasource_cmdline':
cmdline.c:71:79: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
     for (cmdLineArgCount=0 ; *(snoopy_inputdatastorage->argv+cmdLineArgCount) != '\0' ; cmdLineArgCount++);
                                                                               ^~
cmdline.c:71:30: note: did you mean to dereference the pointer?
     for (cmdLineArgCount=0 ; *(snoopy_inputdatastorage->argv+cmdLineArgCount) != '\0' ; cmdLineArgCount++);
                              ^
cc1: all warnings being treated as errors
make[3]: *** [cmdline.lo] Error 1
make[3]: se sale del directorio `/root/snoopy-install-from.git/src/datasource'
make[2]: *** [all-recursive] Error 1
make[2]: se sale del directorio `/root/snoopy-install-from.git/src'
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio `/root/snoopy-install-from.git'
make: *** [all] Error 2

**Comment by gcsgithub** [comment]
its bad code the LHS is a pointer being compared to a zero byte `\0' should be (char *) 0

**Comment by bostjan** [comment]
Moved @jualbacar and @gcsgithub's comments into a new issue #159.

Guys, please don't conflate separate problems inside one ticket, thanks. ;)

**Comment by bostjan** [comment]
That domain was only used as a download source because GitHub was not allowing uploading custom .tar.gz files at the time. Created a release here and converted the install script to use GitHub download URL.
