### ISSUE TITLE
README: How does it work?

### ISSUE THREAD

**Issue by guettli** [a2o/snoopy#147]
I look at the github page and see the docs.

I see how I could compile snoopy. But I have no clue what the next step after compiling looks like.

Please forgive me, if I am blind.

**Comment by r-lindner** [comment]
install-snoopy uses `make enable` which uses `util/snoopy-enable` which writes a line into `/etc/ld.so.preload`

**Comment by bostjan** [comment]
Thanks for jumping in, @r-lindner. I was AFGH (AwayFromGitHub) for too long indeed ;)
