### ISSUE TITLE
change default Snoopy output  in systemd

### ISSUE THREAD

**Issue by tizitizi** [a2o/snoopy#149]
| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | |
| Linux distribution:                 | RHEL             | |
| Distribution version:               | 7.7           | |
| Snoopy version:                     |    snoopy-2.2.6-3.fc24.x86_64.rpm       | |
| Snoopy config file was used:        | yes   | |
| Snoopy threading support enabled:   | FILLIN (yes|no)   | |

## Issue description - How was Snoopy installed

  

distro package

## Issue description - Describe the problem you are having

Snoopy output is /var/log/secure but I would like change with /var/log/snoopy/UID.log as I did on RHEL6 (with rsyslog system)

## Actual result

I have a very big /var/log/secure

**Comment by bostjan** [comment]
No idea what this is about. Feel free to feed snoopy output to rsyslog, and then do advanced filtering/dispatching with rsyslog's filtering/dispatching facilities.

**Comment by liorco300** [comment]
Hi my mail is being spammed with mails and I can’t  unsubscribe I get an
error,
Could you kindly remove me from the mailing list?

Thanks

**Comment by bostjan** [comment]
@liorco300, you yourself have subscribed to notifications from this repository:
![image](https://user-images.githubusercontent.com/107080/95124370-9a757100-0753-11eb-81f5-58994d5c6179.png)

I can't remove you from watching this repository, only you can. Google up how to unwatch a repository, or contact github support.

**Comment by liorco300** [comment]
Yes I know probably with another GitHub account, anyway thanks I will try
and figure it out with GitHub
