### ISSUE TITLE
Unable to Uninstall Snoopy in Ubuntu

### ISSUE THREAD

**Issue by pankajjha** [a2o/snoopy#155]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favourite distribution, it might be out of date)
- [x] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [x] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [x] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86-64            | | 
| Linux distribution:                 | Ubuntu 18.04.3 LTS           | | 
| Distribution version:               |18.04.3 LTS            | | 
| Snoopy version:                     | 2.4.6| I used the stable one| 
| Snoopy config file was used:        |no   | Don't Know| 
| Snoopy threading support enabled:   |  no  |Don't know |

## Issue description - How was Snoopy installed
`rm -f snoopy-install.sh &&
wget -O snoopy-install.sh https://github.com/a2o/snoopy/raw/install/doc/install/bin/snoopy-install.sh &&
chmod 755 snoopy-install.sh &&
./snoopy-install.sh stable`

## Issue description - Describe the problem you are having

I want to uninstall snoopy, but unable to understand the way to do it.
I tried following instructions but failed
`https://www.thelinuxfaq.com/ubuntu/ubuntu-17-04-zesty-zapus/snoopy?type=uninstall`
`https://www.crybit.com/how-to-installuninstall-snoopy-logger-on-unixlinux-server/`

**Comment by bostjan** [comment]
Most likely related to #140. Closing for now, reopen if the issue still persist, but do provide the actual error (from the snoopy-install.log file that the installer generates).

**Comment by bostjan** [comment]
PS: Manual uninstallation is simple - remove snoopy entry from the `/etc/ld.so.preload` file.

**Comment by bostjan** [comment]
Let me elaborate a bit, if anyone else stumbles upon this support request:
- Random guides on the internet are not supported, as they can be outdated, old, or just plain wrong.
- While there are efforts for packaging Snoopy into distributions going on, they are not yet connected to Snoopy development in any meaningful way. Fell free to suggest a viable method that would provide simple means of creating and adding latest Snoopy packages into main distributions' package repos.

Therefore, if Snoopy was installed with a distribution's native package installer, and uninstallation does not work, contact the maintainer of that package.

However, in a pinch, manual purge of Snoopy can still be performed (albeit it's ugly) by:
- Removing the Snoopy entry from `/etc/ld.so.preload`
- Deleting the `libsnoopy.*` files from wherever you have installed them
- Deleting the `snoopy.ini` from wherever you have installed them
- Restarting the system.

This uninstallation is described in the [INSTALL](https://github.com/a2o/snoopy/blob/master/doc/INSTALL.md) document.
