### ISSUE TITLE
Snoopy don't log anything on FreeBSD

### ISSUE THREAD

**Issue by xenofree** [a2o/snoopy#156]
Hi,

## Issue description - How was Snoopy installed

Snoopy installed on FreeBSD 12.1 through port or pkg (can't compile it on Freebsd, features.h is missing).

## Issue description - Describe the problem you are having

Snoopy don't log anything.

## Steps to reproduce

/etc/ld.so.preload doesn't exist on FreeBSD so I export LD_PRELOAD=/usr/local/lib/libsnoopy.so. I don't have any error message but this don't log anything.
Snoopy version < 2.0 compile and work greats on BSD. But not the newer version.

Do you have any idea why ?

Regards

**Comment by bostjan** [comment]
No idea what's going on, and no FreeBSD system at hand either.  A PR with a fix for the missing `features.h` file would be appreciated. Closing for now, as this seems unactionable at the moment.
