### ISSUE TITLE
Snoopy Fails to Build with GCC-10

### ISSUE THREAD

**Issue by MarcosFouces** [a2o/snoopy#157]
Hello

I forward you this bug from Debian.
The package fails to build in a test rebuild on at least amd64 with gcc-10/g++-10, but succeeds to build with gcc-9/g++-9.
The full build log can be found at:
http://people.debian.org/~doko/logs/gcc10-20200225/snoopy_2.4.6-6_unstable_gcc10.log
Greetings, 
Marcos

**Comment by bostjan** [comment]
@MarcosFouces, can you retry with version 2.4.7?
Which Debian version are you using for gcc-10?

**Comment by bostjan** [comment]
Fixed in 2.4.8:
https://github.com/a2o/snoopy/releases/download/snoopy-2.4.8/snoopy-2.4.8.tar.gz

Thanks for reporting this, Marcos.
