### ISSUE TITLE
log also subprocess commands such as nodejs shell

### ISSUE THREAD

**Issue by DanOfir** [a2o/snoopy#189]
Hi,

I am wondering if this tool can also log commands executed inside nodejs or ruby shells, couldn't find an answer, and by testing it i see it doesn't, so just wondering if this can be enabled somehow

**Comment by bostjan** [comment]
@DanOfir, are node and ruby shells those CLI tools that allow you to enter node/ruby code and they evaluate it as you enter it (once you hit the return key)? If that's the case, then the answer is `no, unless those "commands" (in reality they are usually just function calls) trigger a process creation mechanism underneath`.

If not, can you elaborate on the use case with a short example that I can test on my end?
