### ISSUE TITLE
Error messages, adding a new user

### ISSUE THREAD

**Issue by MarcoStagno** [a2o/snoopy#191]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#latest-version (not the latest Snoopy version packaged by your favorite distribution, which might be out of date)
- [X] I have read Snoopy's documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [X] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [X] I have searched existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics
| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | |
| Linux distribution:                 | Ubuntu            | |
| Distribution version:               | 20.04            | |
| Snoopy version:                     | 2.4.11            | |
| Snoopy config file was used:        | yes   | |
| Snoopy threading support enabled:   | no   | |

## Issue description - How was Snoopy installed
        - install-snoopy.sh

## Issue description - Describe the problem you are having
When I add a new user in the system, I got these errors:

```
(...)
Enter the new value, or press ENTER for the default
	Full Name []: 
	Room Number []: 
	Work Phone []: 
	Home Phone []: 
	Other []: 
chfn: nscd did not terminate normally (signal 11)
chfn: nscd did not terminate normally (signal 11)
chfn: sss_cache did not terminate normally (signal 11)
chfn: nscd did not terminate normally (signal 11)
chfn: sss_cache did not terminate normally (signal 11)
Is the information correct? [Y/n] y
(...)
```

I don't get these errors if I switch back to the release 2.4.10 

## Steps to reproduce
Install 2.4.11 and add a new user in the system; I use a virtualized Ubuntu on AWS or VMWare

## Expected result
Avoid error messages

**Comment by bostjan** [comment]
Ouch!

Thanks @MarcoStagno for reporting this - it's an undesired side product of #179.

#192 should fix this issue. I'll release v2.4.12 (that will contain this fix) soon.

**Comment by bostjan** [comment]
@MarcoStagno, Snoopy 2.4.12 has been released, containing the fix for this issue. Thanks again for reporting it.

**Comment by MarcoStagno** [comment]
Thank you so much!
