### ISSUE TITLE
What is the limit the snoopy can log the commands?

### ISSUE THREAD

**Issue by TANKIANAUN** [a2o/snoopy#193]
Hi if I use it without closing my linux, may i know what is the maximum commands can be log?
What would be the limits for the overwrite of old log happens automatically?

**Comment by bostjan** [comment]
I am not 100% sure what exactly are you asking (the question is a bit unclear), but let me attempt to answer what I think you had in your mind:
- If you are asking about _how much_ logs can Snoopy generate, the answer is "unlimited". Snoopy does not care about that, all it does is capture the executed commands, and pass the data to the logging subsystem. Your logging subsystem should be (and usually is, via `logrotate`) configured to rotate old log files, making that "unlimited" size into something manageable. But if you redirect Snoopy output somewhere where `logrotate` (or any similar log rotation software) does not take care of expunging old logs, then Snoopy will eventually fill up your entire disk space.

I hope this helps.
