### ISSUE TITLE
different formats for %{datetime} 

### ISSUE THREAD

**Issue by ky4k0b** [a2o/snoopy#194]
it would be great to have an option of setting different formats for timestaps not only ISO 8601
for example I use the following format for all my logs YYYY-MM-DD HH:MM:SS

**Comment by bostjan** [comment]
Ha, my first thought was `wait, isn't this already supported?` :)

Good suggestion, @ky4k0b, thanks. Should happen in the next version. If you want to give it a shot with a PR, the relevant code is in the `src/datasource/datetime.*` files.

**Comment by bostjan** [comment]
@ky4k0b, the feature has been merged. Can you build Snoopy from the latest master and let me know if you spot any issues?

**Comment by ky4k0b** [comment]
@bostjan 
just what I needed. Thanks for quick fix

**Comment by bostjan** [comment]
Released in https://github.com/a2o/snoopy/releases/tag/snoopy-2.4.13.
