### ISSUE TITLE
snoopy can't log commands created by java

### ISSUE THREAD

**Issue by MrJeffyw** [a2o/snoopy#211]
my java location: /usr/lib/jvm/jre/bin/java
And libsnoopy.so has been loaded by java:
[root@stupid-0001 tmp]# ldd /usr/lib/jvm/jre/bin/java
	linux-vdso.so.1 =>  (0x00007fffe21e5000)
	/usr/lib64/libssh-monitor.so (0x00007f135c3a1000)
	/usr/local/lib/libsnoopy.so (0x00007f135c194000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f135bf78000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f135bd62000)
	libjli.so => /usr/lib/jvm/jre/bin/../lib/amd64/jli/libjli.so (0x00007f135bb53000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f135b94f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f135b581000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f135b279000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f135af77000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f135ad61000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f135c7b4000)

And nothing is filtered in snoopy.ini

but when i execute command by java, snoopy can't log anything.

**Comment by bostjan** [comment]
@MrJeffyw, thanks for pointing out Snoopy is indeed (pre)loaded as expected.

Can you try to produce an `strace` output of your Java application around the time when the application executes that external command? That should give us clues if Snoopy is actually doing anything, or maybe simply trying to put its output in an unexpected location.

PS: Is your Java application chroot-ed by any chance, or containerized in some fashion that would prevent Snoopy from accessing all the expected environment (config file, `/dev/log` socket or the target log file)? Seccomp/Apparmor maybe?

**Comment by MrJeffyw** [comment]
> @MrJeffyw, thanks for pointing out Snoopy is indeed (pre)loaded as expected.
> 
> Can you try to produce an `strace` output of your Java application around the time when the application executes that external command? That should give us clues if Snoopy is actually doing anything, or maybe simply trying to put its output in an unexpected location.
> 
> PS: Is your Java application chroot-ed by any chance, or containerized in some fashion that would prevent Snoopy from accessing all the expected environment (config file, `/dev/log` socket or the target log file)? Seccomp/Apparmor maybe?


I solved this problem.
The java process does not have the permission to write snoopy log, which I set is /var/log/processlog. After I executed "chmod +777 /var/log/processlog", it works!
Thanks!

**Comment by bostjan** [comment]
Good to hear you've solved the issue, and thanks for sharing your insight.
