### ISSUE TITLE
Just a little question about reboot (or not) after installation.

### ISSUE THREAD

**Issue by pju51** [a2o/snoopy#212]
Hello,

I want to log user account commands on my servers, and snoopy seems to fit my needs perfectly.
but I would like to install snoopy without rebooting, is it possible?

I have tried it without rebooting, it works, I log the user commands well! so why reboot my servers? If I don't reboot my servers, what will I miss?

thank you for your clarifications.

**Comment by bostjan** [comment]
Hey @pju51,

_technically_, you don't need to reboot your system _if_ you restart _all_ the services that are currently running. If you do that, all the programs running on your system will have the Snoopy shared library loaded in their memory, and will thus log any programs they execute. However, if you _don't_ do that, programs already running from before Snoopy was installed may miss commands you'd want them to log.

**Comment by pju51** [comment]
Thanks your for your clarification!
