### ISSUE TITLE
Corrupted log entries when cwd no longer exists

### ISSUE THREAD

**Issue by tsilen** [a2o/snoopy#24]
This is with the current deb package for ubuntu 12.04 (1.8.0-3) so it could be that it's fixed already in later versions, but thought I would let you know just in case.

If the cwd where the program was started has been removed, snoopy log entry gets corrupted and instead of cwd we see some other data apparently from /proc/pid/status:

``````
Nov  3 10:50:53 app-02 snoopy[32273]: [uid:991 sid:10362 tty: cwd:#011  674656 kB#012VmLck:#011       0 kB#012VmPin:#011       0 kB#012VmHWM:#011  148236 kB#012VmRSS:#011  148236 kB#012VmData:#011  498252 kB#012VmStk:#011     136 kB#012VmExe:#011       4 kB#012VmLib:#011   15720 kB#012VmPTE:#011     720 kB#012VmSwap:#011   18564 kB#012Threads:#0111#012SigQ:#0110/241213#012SigPnd:#0110000000000000000#012ShdPnd:#0110000000000000000#012SigBlk:#0110000000000000000#012SigIgn:#0110000000008300801#012SigCgt:#0110000000182007646#012CapInh:#0110000000000000000#012CapPrm:#0110000000000000000#012CapEff:#0110000000000000000#012CapBnd:#011ffffffffffffffff#012Cpus_allowed:#0117fff#012Cpus_allowed_list:#0110-14#012Mems_allowed:#01100000000,00000001#012Mems_allowed_list:#0110#012voluntary_ctxt_switches:#0110#012nonvoluntary_ctxt_switches:#0110#012#031�#003 filename:/path/to/file]: ...```
``````

**Comment by bostjan** [comment]
I just rechecked this with master, datasource returns error, as it should.

The additional benefit would be if datasource returned actual error message about CWD not being present anymore, but this excercise is left for some diligent contributor :)

b.
