### ISSUE TITLE
i686 builds of snoopy

### ISSUE THREAD

**Issue by wpoely86** [a2o/snoopy#255]
Currently the RPM repositories only contain a x86_64 version of snoopy. Would it be possible to also add a i686 version?

**Comment by bostjan** [comment]
@wpoely86, every time I get my hopes up with `yes, I _finally_ got rid of this ancient 32-bit stuff, good riddance!`, inevitably someone comes along asking for it :)))

Here is my PoV, though:
- Generally we could add the i686 version, I think.
- I don't really care for 32-bit architectures much, but I do keep the i686 CI workflow somewhere to make sure we don't get too comfy in the 64-bit world. 
- If the PR comes along that:
  - Adds workflows for building 32-bit binaries
  - Does not destroy the structure of existing repositories
  - Works without me needing to do much (preferably anything beyond merging)
- Then why not.
- (However, I am not promising my commitment to keeping it running smoothly, and if I get annoyed by its potential future failures enough, I may just wipe it without any prior notice. That is, unless someone else commits to making things run smoothly, which would be nice.)

PS: What's the use case here, why are you not using the 64-bit option?

**Comment by bostjan** [comment]
Closing, no response.
