### ISSUE TITLE
Install in cloud-init or using shell script

### ISSUE THREAD

**Issue by johnz0r** [a2o/snoopy#268]
Hello,
I'm very sorry to create an issue for that but i've tried many things and can't get it working.

I am trying to install snoopy on all our server using a cloud-init script and i can't get it to work due to the security interactive prompt. I am using apt and official debian repository.

I've tried the classicals:
yes | apt install snoopy
sudo DEBIAN_FRONTEND=noninteractive apt install snoopy -y

The software is installed but not activated. 
Do you have any idea how i can get it to work ?

Huge thank you !
J

**Comment by 411x** [comment]
Hello,

You can use debconf-set-selections  
(check the template file in the debian package).

```
echo "snoopy snoopy/install-ld-preload boolean true" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt-get install snoopy -y
```

should work.

**Comment by johnz0r** [comment]
Hello 411x,

Huge thank you !
That works perfectly :)

J

**Comment by bostjan** [comment]
@411x, thanks for stepping up & sharing this very useful information.
