### ISSUE TITLE
Why Snoopy don't log by default non-root user commands ?

### ISSUE THREAD

**Issue by AndriiY-SK** [a2o/snoopy#276]
## Checklist before starting to submit this support request

I confirm that:
- [X] I am requesting support! :)
- [X] I have tested this with the [latest stable Snoopy version](https://github.com/a2o/snoopy/releases/latest) (or the latest master build).
- [X] I have checked the [FAQ](https://github.com/a2o/snoopy/blob/master/doc/FAQ.md).
- [X] I have read Snoopy's documentation [here](https://github.com/a2o/snoopy/blob/master/README.md) and [here](https://github.com/a2o/snoopy/tree/master/doc).
- [ ] I have searched [Snoopy issues](https://github.com/a2o/snoopy/issues?q=is%3Aissue) for an existing issue that matches my problem, and found none.

### Environment

Ubuntu version: 22.04

Version `snoopyctl version`
```
Snoopy CLI tool version: 2.5.1
Snoopy library version:  2.5.1 (path: /usr/local/lib/libsnoopy.so)
```

## Issue reproduction steps

`snoopyctl conf`

```
; Options from config file (or defaults): /etc/snoopy.ini
[snoopy]
error_logging = yes
filter_chain = 
message_format = [login:%{login} ssh:(%{env:SSH_CONNECTION}) sid:%{sid} tty:%{tty} (%{tty_uid}/%{tty_username}) uid:%{username}(%{uid})/%{eusername}(%{euid}) cwd:%{cwd}]: %{cmdline}
output = file:/var/log/snoopy.log
syslog_facility = AUTHPRIV
syslog_ident = snoopy
syslog_level = DEBUG
```

Command libraries `ldd /bin/ls` from non-root user
```
	linux-vdso.so.1 (0x00007fff5cbfc000)
	/usr/local/lib/libsnoopy.so (0x000078a94258d000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x000078a942550000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000078a942200000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x000078a9424b9000)
	/lib64/ld-linux-x86-64.so.2 (0x000078a9425c3000)
```

## Actual result

I see only next logs logs and commands from root user
```
[login:(unknown) ssh:((undefined)) sid:904 tty:(none) ((none)/(none)) uid:root(0)/root(0) cwd:/opt/<BINARY_NAME>]: /sbin/ip route get <IP>
[login:(unknown) ssh:((undefined)) sid:904 tty:(none) ((none)/(none)) uid:root(0)/root(0) cwd:/opt/<BINARY_NAME>]: /sbin/ip route get <IP>
[login:(unknown) ssh:((undefined)) sid:904 tty:(none) ((none)/(none)) uid:root(0)/root(0) cwd:/opt/<BINARY_NAME>]: /sbin/ip route get <IP>
[login:(unknown) ssh:((undefined)) sid:904 tty:(none) ((none)/(none)) uid:root(0)/root(0) cwd:/opt/<BINARY_NAME>]: /sbin/ip route get <IP>
[login:(unknown) ssh:((undefined)) sid:904 tty:(none) ((none)/(none)) uid:root(0)/root(0) cwd:/opt/<BINARY_NAME>]: /sbin/ip route get <IP>
```

**Comment by bostjan** [comment]
Hey @AndriiY-SK, it seems like your `/var/log/snoopy.log` file is owned by root and has access permissions set up in such a way that no other user can write to it (0644 or 0640, which is the default most of the time).

If you want such a setup (Snoopy using the `file:...` output specification, not using Syslog), you'll have to give the `/var/log/snoopy.log` file the appropriate permissions to achieve your goal (i.e. `0666` - yeah, I know, not the safest suggestion).

**Comment by AndriiY-SK** [comment]
thanks !
