### ISSUE TITLE
repository 404

### ISSUE THREAD

**Issue by celevra** [a2o/snoopy#279]
Hi,

in the install manual there should be an ubuntu repository:
```
https://a2o.github.io/snoopy-packages/repo/ubuntu
```

bit it gives an 404

regards

**Comment by celevra** [comment]
Ok than the documentation is a little bit ahead ;-)
https://github.com/a2o/snoopy/blob/master/doc/install-from-repo.md#ubuntu

Thanks

**Comment by bostjan** [comment]
@celevra, crap, you're right! :)))

I'll reopen this issue and close it once Noble package is out.

**Comment by bostjan** [comment]
@celevra, Snoopy Logger package for Ubuntu 24.04 is now available.
