### ISSUE TITLE
(informational) Pulseaudio fills logs with snoopy installed

### ISSUE THREAD

**Issue by sykosoft** [a2o/snoopy#29]
If, like us, you have users running desktop environments, you'll find pulseaudio filling your logs because of snoopy.

In this instance:

In /etc/pulse/client.conf
If it exists, uncomment "autospawn" and change to "no", otherwise, add a line

"autospawn = no"

(This is not a bug, but is informational, and I saw no where else to put it).

**Comment by bostjan** [comment]
Thanks for reporting this issue **and** resolution.

I've refactored the documentation (desperately needed) and added this to Snoopy FAQ: https://github.com/a2o/snoopy/blob/master/doc/FAQ.md.

I hope that other affected users will find it easily enough :)

PS: I do not use Snoopy on my desktops, but: how much Snoopy content does PulseAudio generate per second?
