### ISSUE TITLE
ppid does not work

### ISSUE THREAD

**Issue by ajzach** [a2o/snoopy#33]
I tried to show the ppid but not displayed correctly, if I enter to a machine via ssh, the ppid would not have to be the ppid of sshd?

**Comment by bostjan** [comment]
I think "sid" would be more appropriate input provider for your use case, but still it returns the PID of console shell process (bash), not of sshd that created this bash process.

ppid simply means "parent pid", which is PID of the process that created the current process, not the SSHD's pid specifically.

If you are looking for data provider that traverses upwards the process tree until it finds as ssh(d), process, you will not find one available ATM. Patches are welcome though :)

b.

**Comment by bostjan** [comment]
This issue was superseded and fixed by pull request #37.
