### ISSUE TITLE
AM_PROG_AR not found in library

### ISSUE THREAD

**Issue by BIAndrews** [a2o/snoopy#38]
# ./autogen.sh 

Starting AutoTools run:

+ '[' -d autom4te.cache ']'
+ rm -rf autom4te.cache
+ autoreconf -i
configure.ac:13: warning: macro `AM_PROG_AR' not found in library
libtoolize: `./ltmain.sh' is newer: use `--force' to overwrite
libtoolize: `m4/libtool.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltoptions.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltversion.m4' is newer: use `--force' to overwrite
libtoolize: `m4/lt~obsolete.m4' is newer: use `--force' to overwrite
libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'
configure.ac:13: warning: macro `AM_PROG_AR' not found in library
configure.ac:13: error: possibly undefined macro: AM_PROG_AR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

-------

Any idea why the build isn't working? I cloned from master/latest. I'll try a tag next.

**Comment by tkimball83** [comment]
I've worked around this in my spec file by doing the following:

sed -i -e 's/^AM_PROG_AR/#AM_PROG_AR/' configure.ac

https://github.com/tkimball83/rpmbuild/blob/master/SPECS/snoopy.spec

**Comment by BIAndrews** [comment]
Perfect thanks!

**Comment by bostjan** [comment]
Which distro/autotools version are you using?

I had some issues with this one too. It might be better to disable it by default and adjust spec file, or maybe rewrite it manually. Opinions welcome.

B.

**Comment by BIAndrews** [comment]
CentOS 6.6 64bit 

autoconf (GNU Autoconf) 2.63
GNU Make 3.81
automake (GNU automake) 1.11.1

I'm not sure what distro requires it but if your base dev box is a RHEL flavor I would disable it by default.

**Comment by bostjan** [comment]
It is required by debian/ubuntu packaging, not by snoopy itself.

B.

**Comment by bostjan** [comment]
@BIAndrews @tkimball83 
If someone has a sane proposal on how to make this inclusion conditional, based on which distro is detected below, it would be splendid.

Otherwise I am more inclined to removing this from configure.ac and fixing spec file, so it reenables _AR macro when it is actually needed.

b.
