### ISSUE TITLE
Ubuntu installer prompt

### ISSUE THREAD

**Issue by epicmmj** [a2o/snoopy#40]
When I install Snoopy 1.8.0 on Ubuntu 12.04 using Apt package manager, I get the following scary prompt:

"Snoopy is a library that can only reliably do its work if it is mandatorily preloaded via /etc/ld.so.preload. Since this can potentially do harm to the system, your consent is needed"  

Can someone shed some light as to what kind harm may this cause to a system? I've never encountered any issues with Snoopy, and I want to make sure I could use it in a production environment.  

![screen shot 2015-04-16 at 5 36 37 pm](https://cloud.githubusercontent.com/assets/11985885/7194165/49a402f4-e45f-11e4-91bd-bed14161c7ff.png)

**Comment by bostjan** [comment]
None of Snoopy versions except the latest one (2.2.7 now, 2.2.8 tomorrow) are supported, keep that in mind. This is an open source project, so responsibility for your production environment is entirely yours.

That said, go ahead and read Snoopy's source code to understand how it actually works and what the inherent dangers are. This should be done using current master branch in git repo. The main content of Snoopy resides in src/libsnoopy.c - system calls execv() and execve() are overloaded with Snoopy-specific versions, which, when called, will first do the logging and then forward the execution to actual system calls as if nothing happened. Everything else that happens between original (fake execv()) and subsequent call (to real execv()) is just not that important (Snoopy reads config file, gathers data, formats log message, sends it to syslog, etc).

If you want a condensed view of how Snoopy works, look at the source code of some older release, where everything is still contained in one file. For example here, version 1.7.10:
https://github.com/a2o/snoopy/blob/8bbb54a84fa20f257a02657dfe130ded7dfc15be/snoopy.c

The danger that your message is talking about is this: should something bad happen during data-gathering,-message-formatting,-filtering-and-logging phase of Snoopy, program that you are trying to run might not be executed.

Is snoopy used in production? I use it, for a couple of years already, on all systems, all the time, and always the latest version. But then again, I maintain it, so I generally know when new versions are released:) From what I can gather I can see around 10 unique-IP-installs per day, so I can safely assume some other people are using it too, probably in production too.

Are there any bugs in Snoopy? Probably. I am just ironing out one (2.2.8 will contain the fix), then probably some malloc() calls are not checked if they actually succeeded, which might cause problems on OOM condition (patches welcome). There might be other ones which I have not predicted.

How to install it?
Please do not use apt-get method as those versions are ANCIENT. Especially versions before 1.9.0, as they contain a serious bug which causes RH systems to deadlock on boot/shutdown.

The simple installation procedure for the latest version is available here (install script):
https://github.com/a2o/snoopy

If that does not fit your need, and you need to use apt-get, then do build your own package, but again - use the latest versions. Here is even a contributed build files in contrib/debian/ (I just merged those files, it was created by Sébastien Gross - tkimbal83 user on github, ask there if you encounter problems).

If you have any bugs and questions to report, do it only for latest Snoopy versions. This is also the reason I am closing this issue.

b.

**Comment by etapia** [comment]
Thank you for the quick response. It was very helpful.

**Comment by epicmmj** [comment]
Thank you for your quick response. It is very helpful.
