### ISSUE TITLE
only logs root

### ISSUE THREAD

**Issue by vladnosferatu** [a2o/snoopy#67]
hello

snoopy only logs root , how i change it to log all users ? 

and i only what to log the command and not what the sheel script do inside, 

thanks

**Comment by bostjan** [comment]
Which version are you using? How did you install it? Please specify exact procedure, and (if used), paste relevant snoopy.ini parts (not the comments, only actual settings).

Second part: "and i only what to log the command and not what the sheel script do inside,"
Good luck with this one. Currently there is no filter implemented to do this, and you are encouraged to implement one, but it will not be easy (Snoopy does not have a way to determine whether particular command was executed as part of script or by hand). If you can pull it off, contribution is very welcome.

b.

**Comment by vladnosferatu** [comment]
v2.3.0

manage to know what causes the problem
if i chooge the lof to 

output = file:/var/log/snoopy.log
will only record root id

but on /var/log/secure are the all users


can you add on your filter GID ?

**Comment by bostjan** [comment]
Your output: if you use file output, you have to have adequate permissions to write to it as regular user too. Use syslog to be more flexible and avoid having files with 666 permissions.

Yes, filters are in C.

Contributing:
https://github.com/a2o/snoopy/blob/master/doc/CONTRIBUTING.md
- see src/filter/only_uid.c and src/filter/exclude_uid.c for examples

b.

**Comment by vladnosferatu** [comment]
with 666 permissions, users can delete the log :(

ok thanks a lot

**Comment by vladnosferatu** [comment]
can you make a filter for GID, 
i dont have very experience on C  :(

**Comment by bostjan** [comment]
Me neither :)

This is open source. I can create it, but unfortunately I do not have time to. There is commercial support available, if you are interested.
