### ISSUE TITLE
Complie error on OpenSuSE and SLES

### ISSUE THREAD

**Issue by tparkercbn** [a2o/snoopy#68]
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -Wall -Werror -g -O2 -MT misc.lo -MD -MP -MF .deps/misc.Tpo -c misc.c  -fPIC -DPIC -o .libs/misc.o
cc1: warnings being treated as errors
misc.c: In function 'snoopy_string_append':
misc.c:112: error: call to function 'snoopy_error_handler' without a real prototype
error.h:28: note: 'snoopy_error_handler' was declared here

**Comment by tparkercbn** [comment]
I was able to fix it by changing the prototype in error.h to:

/*
 * Error-handling functions
 */
void snoopy_error_handler(char *s);

**Comment by bostjan** [comment]
A, I see, the argument is missing in prototype.

Hmm, I wonder why this has not yet cropped up before - what configure flags did you use, or, more general, how did you try to compile it?

Also, can you submit a pull request with a fix so git history will keep track of person responsible for finding and fixing this bug? Tnx.

https://github.com/a2o/snoopy/blob/master/doc/CONTRIBUTING.md

b.

**Comment by tparkercbn** [comment]
I just followed the instructions for downloading and installing the
latest version using the snoopy-install.sh script with no modifications
at first.  I then downloaded the source tarball and ran ./configure and make

I will see if I can figure out how to do the pull request.  If it's
easier for you to just fix it I don't need any credit :)

Tom

**Comment by bostjan** [comment]
Fixed in 2.3.1.

Thanks for reporting it.

b.
