### ISSUE TITLE
New filter problem

### ISSUE THREAD

**Issue by liorco300** [a2o/snoopy#71]
Hi,
Added new filter only_tty which shows comands from only_tty sessions
changed the following Files:
[root@il-zabbix snoopy]# find . -name "*.*" | xargs grep -i "only_tty" 
./configure.ac:SNOOPY_CONFIGURE_FILTER_ENABLE( [only_tty],         [This filter passes only messages generated by tty.])
./etc/snoopy.ini.in:; - filter_chain = "only_tty:0"          # Log only tty sessions
./etc/snoopy.ini.in:;filter_chain = "only_tty:0"
./src/filter/Makefile.am:### Filter: only_tty
./src/filter/Makefile.am:if FILTER_ENABLED_only_tty
./src/filter/Makefile.am:         only_tty.c \
./src/filter/Makefile.am:         only_tty.h
./src/filter/only_tty.c: * File: snoopy/filter/only_tty.c
./src/filter/only_tty.c: * SNOOPY FILTER: only_tty
./src/filter/only_tty.c:#include "only_tty.h"
./src/filter/only_tty.c:int snoopy_filter_only_tty (char *msg, char *arg)
./src/filter/only_tty.h: * File: snoopy/filter/only_tty.h
./src/filter/only_tty.h: * SNOOPY FILTER: only_tty
./src/filter/only_tty.h:int snoopy_filter_only_tty (char *msg, char *arg);
./src/filterregistry.c:#ifdef SNOOPY_CONF_FILTER_ENABLED_only_tty
./src/filterregistry.c:#include "filter/only_tty.h"
./src/filterregistry.c:#ifdef SNOOPY_CONF_FILTER_ENABLED_only_tty
./src/filterregistry.c:    "only_tty",
./src/filterregistry.c:#ifdef SNOOPY_CONF_FILTER_ENABLED_only_tty
./src/filterregistry.c:    snoopy_filter_only_tty,

[root@il-zabbix snoopy]# ./bootstrap.sh

Starting AutoTools run:

+ '[' -d autom4te.cache ']'
+ '[' '!' -d build/m4 ']'
+ autoreconf -i -v
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I build/m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory

problem with ./bootstrap please help :) 

Thanks

**Comment by bostjan** [comment]
Of the top of my head these packages need to be installed (names are for Ubuntu):
- autoconf
- automake
- autotools-dev
- libtool
- and of course the standard: gcc gzip make tar wget
- socat (for test suite)

I think you are missing either autoconf or autotools-dev.

**Comment by liorco300** [comment]
Hi updated all,
Still i have a problem:


[root@il-zabbix snoopy]#  ./bootstrap.sh

Starting AutoTools run:

+ '[' -d autom4te.cache ']'
+ rm -rf autom4te.cache
+ '[' '!' -d build/m4 ']'
+ autoreconf -i -v
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I build/m4
configure.ac:60: warning: macro `AM_PROG_AR' not found in library
configure.ac:10: warning: AC_INIT: not a literal: m4_esyscmd_s(echo $(./build/get-git-version.sh))
autoreconf: configure.ac: tracing
configure.ac:10: warning: AC_INIT: not a literal: m4_esyscmd_s(echo $(./build/get-git-version.sh))
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build/aux'.
libtoolize: copying file `build/aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build/m4'.
libtoolize: copying file `build/m4/libtool.m4'
libtoolize: copying file `build/m4/ltoptions.m4'
libtoolize: copying file `build/m4/ltsugar.m4'
libtoolize: copying file `build/m4/ltversion.m4'
libtoolize: copying file `build/m4/lt~obsolete.m4'
libtoolize: `AC_PROG_RANLIB' is rendered obsolete by `LT_INIT'
configure.ac:60: warning: macro `AM_PROG_AR' not found in library
configure.ac:10: warning: AC_INIT: not a literal: m4_esyscmd_s(echo $(./build/get-git-version.sh))
autoreconf: running: /usr/bin/autoconf
configure.ac:10: warning: AC_INIT: not a literal: m4_esyscmd_s(echo $(./build/get-git-version.sh))
configure.ac:12: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:35: error: possibly undefined macro: AM_PROG_AR
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by bostjan** [comment]
What is your OS/version?

**Comment by bostjan** [comment]
You should use recent version of OS to develop Snoopy. Namely autoconf version 2.69 and automake version 1.11.

I tried building it from git on Slackware 12.2 (oldest system I have currently access to, from 2008) and I needed to do 4 modifications to make it work:

1. AM_PROG_AR (fixed in master, just pull it)
2. AC_PROG_LIBTOOL (fixed in master too, pull it)
3. 


```diff
# git diff
diff --git a/configure.ac b/configure.ac
index 713f6fe..5675dde 100644
--- a/configure.ac
+++ b/configure.ac
@@ -9,7 +9,7 @@
 AC_PREREQ([2.63])
 AC_INIT(
     [Snoopy Logger],
-    m4_esyscmd_s(echo $(./build/get-git-version.sh)),
+    [2.3.1-master-dirty],
     [https://github.com/a2o/snoopy/issues/],
     [snoopy],
     [https://github.com/a2o/snoopy/])
@@ -21,7 +21,7 @@ AC_CONFIG_SRCDIR([src/libsnoopy.c])   # Check if we are in correct directory tre
 AC_CONFIG_AUX_DIR([build/aux])
 AC_CONFIG_MACRO_DIR([build/m4])
 m4_include([build/snoopy.m4])
-AM_INIT_AUTOMAKE([1.11 gnu silent-rules subdir-objects -Wall -Werror])
+AM_INIT_AUTOMAKE([1.10 gnu subdir-objects -Wall -Werror])
 
 
 ### Silent make output
@@ -70,7 +70,7 @@ dnl
 m4_ifdef([AM_PROG_AR], [AM_PROG_AR])
 
 dnl Enable libtool
-LT_INIT([disable-static])
+#LT_INIT([disable-static])
 
 
 

```

**Comment by bostjan** [comment]
Closing this for now. Reopen if/when it becomes actual again.

b.
