### ISSUE TITLE
Too strict executable bit check on $LIBDIR/libsnoopy.so in snoopy-enable.in

### ISSUE THREAD

**Issue by evgkrsk** [a2o/snoopy#73]
==8<======================================================
root@thinkpad /etc #snoopy-enable 

SNOOPY ERROR: /usr/lib64/libsnoopy.so is not installed or is not executable

[1]    29079 exit 1     snoopy-enable
root@thinkpad /etc #ls -l /usr/lib64/libsnoopy*
lrwxrwxrwx 1 root root    18 May 27 17:52 /usr/lib64/libsnoopy.so -> libsnoopy.so.0.0.0
lrwxrwxrwx 1 root root    18 May 27 17:52 /usr/lib64/libsnoopy.so.0 -> libsnoopy.so.0.0.0
-rw-r--r-- 1 root root 44504 Apr 24 01:27 /usr/lib64/libsnoopy.so.0.0.0
==8<======================================================

i.e., not all systems/toolchains needs/sets executable bit on shared objects. So, checking on presence of +x bit on libsnoopy.so is too strict and don't work in some cases. I think that right thing is to check presense (and, maybe, readability?) of libsnoopy.so. Patch is trivial (one-char).

**Comment by bostjan** [comment]
Tnx for report.

Which distro/version are you using?

B.

**Comment by liorco300** [comment]
Hi,

[lior@il-zabbix ~]$ uname -r
2.6.32-358.6.1.el6.x86_64
On May 27, 2015 22:13, "Boštjan Škufca" <notifications@github.com> wrote:

> Tnx for report.
>
> Which distro/version are you using?
>
> B.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/a2o/snoopy/issues/73#issuecomment-106039070>.
>

-- 
Gigya <http://www.gigya.com/> | The Leader in Customer Identity Management
2015 CRM Watchlist Winner 
<http://finance.yahoo.com/news/gigya-named-2015-crm-watchlist-165815241.html>

**Comment by bostjan** [comment]
This is only kernel, it has very little to do with Snoopy :)
Linux distribution (Debian, CentOS, Fedora, Ubuntu, SLES, etc) and its version was what I was asking for.

Anyway, fixed in commit 66d18205b746f73c24befd7f121298a2e542d1d6, and just released 2.3.2 that contains this fix.

b.

**Comment by evgkrsk** [comment]
Little addition: s/ or is not executable/ or is not readable/

**Comment by bostjan** [comment]
Fixed in master, tnx for remark.
