### ISSUE TITLE
More expressive filtering, separated from message mangling

### ISSUE THREAD

**Issue by bostjan** [a2o/snoopy#76]
Filtering is currently available and serves two purposes at once:
- decide whether message is passed to output or dropped
- message content mangling

The problem with this approach is that message needs to be generated before filters decide whether it will be logged or not, thus wasting resources.

Current filters should be split into two separate entities:
- filters, that are executed before message generation
- manglers, that mangle either final message, or certain datasource output only.

Filtering should also be made more expressive, with the use of braces and && and || operators, enabling something like:
filter_chain = "(uid=0)||(gid:100,101)"

Mangling is described in issue #56. 

There is a possibility that we keep filters and manglers under the same roof, named "filters", but for whole message mangling a special mangler_chain configuration variable will need to be introduced.

b.

**Comment by vladnosferatu** [comment]
gid ... cool, thanks a lot

**Comment by bostjan** [comment]
@vladnosferatu : What are you talking about?

**Comment by bostjan** [comment]
Partially implemented via 3988de57 from PR #230 (filters can no longer mangle messages, filter processing has been moved to the beginning of the logging process, even before the message is created).

We'll leave it at that for the time being, and revive this ticket if/when need arises.
