### ISSUE TITLE
non-interactive + non-login shell can't record

### ISSUE THREAD

**Issue by pythonsky** [a2o/snoopy#95]
non-interactive and non-login shell exec the command can't find the log

ssh user@ip 'command'

/var/log/auth.log just like 
2015-09-07T14:41:11.806877+08:00 ubuntu sshd[2004]: Received disconnect from 192.168.5.2: 11: disconnected by user
2015-09-07T14:41:11.807433+08:00 ubuntu sshd[2004]: pam_unix(sshd:session): session closed for user root

**Comment by bostjan** [comment]
What is your question?

**Comment by pythonsky** [comment]
by "ssh user@host 'command'"  to exec command on the host, the host is install snoopy,

watch the log(/var/log/auth.log),just like
2015-09-07T14:41:11.806877+08:00 ubuntu sshd[2004]: Received disconnect from 192.168.5.2: 11: disconnected by user
2015-09-07T14:41:11.807433+08:00 ubuntu sshd[2004]: pam_unix(sshd:session): session closed for user root


the exec command is not by record

**Comment by bostjan** [comment]
Either restart SSH server or whole server, or your configuration redirects snoopy log entries somewhere else. Use strace to determine where snoopy sends them (file?) and if it is /dev/log, consult your syslog configuration where those messages actually go.

**Comment by GOPiGal** [comment]
This is a legitimate issue. Neither restart of SSH daemon nor reboot is able to to fix it. The only artifact is execution of sshd.with  -D -R arguments.

Snoopy version: 2.4.6
_/etc/snoopy.ini_ on the **dest.host**
```
[snoopy]
message_format = "timestamp=%{datetime} host=%{hostname} uid=%{uid} uname=%{login} euid=%{euid} euname=%{eusername} pid=%{pid} ppid=%{ppid} tty=%{tty} cwd=%{cwd} cmdline=%{cmdline}"
output = file:/var/log/snoopy.log

```
After the reboot following commands are executed

> dest.host:# aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
> **_rem.host_**:$ ssh pg@dest.host parted
> dest.host:# aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

_/var/log/snoopy.log_
```
timestamp=2018-04-11T16:32:08+0200 host=dest.host uid=0 uname=pg euid=0 euname=root pid=3248 ppid=3247 tty=/dev/pts/4 cwd=/root cmdline=/usr/lib/command-not-found -- aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
timestamp=2018-04-11T16:32:14+0200 host=dest.host uid=0 uname=(unknown) euid=0 euname=root pid=3250 ppid=923 tty=(none) cwd=/ cmdline=/usr/sbin/sshd -D -R
timestamp=2018-04-11T16:32:21+0200 host=dest.host uid=0 uname=pg euid=0 euname=root pid=3280 ppid=3279 tty=/dev/pts/4 cwd=/root cmdline=/usr/lib/command-not-found -- aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
timestamp=2018-04-11T16:32:34+0200 host=dest.host uid=0 uname=pg euid=0 euname=root pid=3283 ppid=2505 tty=/dev/pts/4 cwd=/root cmdline=cat /var/log/snoopy.log

```
_/var/log/auth.log_
```
Apr 11 16:32:17 ubuntu16 sshd[3250]: Accepted password for pg from 172.31.255.236 port 54710 ssh2
Apr 11 16:32:17 ubuntu16 sshd[3250]: pam_unix(sshd:session): session opened for user pg by (uid=0)
Apr 11 16:32:17 ubuntu16 systemd-logind[798]: New session 12 of user pg.
Apr 11 16:32:17 ubuntu16 sshd[3275]: Received disconnect from 172.31.255.236 port 54710:11: disconnected by user
Apr 11 16:32:17 ubuntu16 sshd[3275]: Disconnected from 172.31.255.236 port 54710
Apr 11 16:32:17 ubuntu16 sshd[3250]: pam_unix(sshd:session): session closed for user pg
Apr 11 16:32:17 ubuntu16 systemd-logind[798]: Removed session 12.
```

**Comment by bostjan** [comment]
Works for me:
```
$ ssh root@MYSERVER /bin/echo "adsf"
```

```
$ tail -f /var/log/snoopy.log
...
2018-04-11T19:24:08+00:00 MYSERVER snoopy[14634]: [uid:0 sid:14634 tty:(none) cwd:/ filename:/usr/local/ssh-sys/sbin/sshd]: /usr/local/ssh-sys/sbin/sshd -R
2018-04-11T19:24:08+00:00 MYSERVER snoopy[14636]: [uid:0 sid:14636 tty:(none) cwd:/var/home/root_bostjan filename:/bin/bash]: bash -c /bin/echo adsf
2018-04-11T19:24:08+00:00 MYSERVER snoopy[14636]: [uid:0 sid:14636 tty:(none) cwd:/var/home/root_bostjan filename:/bin/echo]: /bin/echo adsf
```

**Comment by bostjan** [comment]
@pythonsky, check #133 for the answer.
