### ISSUE TITLE
Filter on login

### ISSUE THREAD

**Issue by kippi6171** [a2o/snoopy#98]
All

We are trying out snoopy, looks a power tool, however we have checks that are run by root. Snoopy is currently logging all the commands that the checks are doing. 

What I would like to do is to use the login field and setup a filter. For example I know when these checks run as root the login is (error). I have had ago at building my own filter however it's errors saying it:

/bin/install: symbol lookup error: /usr/local/lib/libsnoopy.so: undefined symbol: snoopy_filter_exclude_login

Is there any information on how to build a new filter, rather than hacking at the code?

Many Thanks

Chris.

**Comment by bostjan** [comment]
I realised that joining content of contribution guidelines and hacking information in one document called CONTRIBUTING.md is confusing, so I did the split.

Hacking guide:
https://github.com/a2o/snoopy/blob/master/doc/HACKING.md

Contributing guide, if you decide it is worth it:
https://github.com/a2o/snoopy/blob/master/CONTRIBUTING.md

b.

PS: What you are trying to achieve might already be done in one of the other filters.

**Comment by kippi6171** [comment]
We just need away to filter out on the login name. I was just going to clone the exclude_uid one and change it to login.

**Comment by kippi6171** [comment]
As far as I can see I have followed the hacking guide, if I am in the filter directory I can do make and it's building the filter:

CC       exclude_rootlog.lo

However I can't seem to link it into snoopy.

uid=0 tty=/dev/pts/0 login=vagrant cmdline=tail -f /var/log/snoopy.logERROR(Filter not found - exclude_rootlog)

Any pointers would be great.

Thanks

Chris

**Comment by bostjan** [comment]
Hi Chris,

Normally grep for exclude.uid in whole repository and you will see the locations that need your attention, as noted in HACKING.

I can hardly give pointers without looking at your code. Fork Snoopy and commit+push your changes, and I will take a look next week.

b.

**Comment by kippi6171** [comment]
Hi Bostjan

I have managed to get my filter working well, however I have had to build this on a FC21 box, but when I try and build it on Centos 6.7 we get the issue with automake hence having to build it on FC21. If I build the package and then install it on Centos 6.7 of cause I get issues with glib. I am interested in how you package it so that I can build it on 6.7.

Thanks for the help.

Chris.

**Comment by bostjan** [comment]
I usually build Snoopy on every system as it is simple package to build (comparatively).

What issue do you get? Can you install it with install script (it supports git-GITREF) pattern, but you will have to edit it and point it to your git repository)?

b.

**Comment by kippi6171** [comment]
The error I get is:

Last 5 lines of Snoopy installation log file:
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127

On centos 6.7, by default it's automake-1.11

**Comment by kippi6171** [comment]
Doing the pull from git and now getting this error:

configure.ac:10: warning: AC_INIT: not a literal: m4_esyscmd_s(echo $(./build/get-version.sh))
configure.ac:12: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by teon-git** [comment]
A, yeah, this is inconvenient.

As git version of snoopy is intended for development, and most of snoopy
development is either done by me or by people on fairly recent systems, we
have simplified the process by eliminating the need for bumping version
numbers in configure.ac every time a build is needed.

This modification does the trick:
diff --git a/configure.ac b/configure.ac
index b71aa32..07edd5a 100644
--- a/configure.ac
+++ b/configure.ac
@@ -9,7 +9,7 @@
 AC_PREREQ([2.63])
 AC_INIT(
     [Snoopy Logger],
-    m4_esyscmd_s(echo $(./build/get-version.sh)),
+    [2.4.4-my-dev-version],
     [https://github.com/a2o/snoopy/issues/],
     [snoopy],
     [https://github.com/a2o/snoopy/])



--
Boštjan Škufca
Teon d.o.o. | http://teon.si

**Comment by bostjan** [comment]
Allright, I've made some adjustments to "bootstrap.sh" etc.

Use commit b067e84d61d9ad30b39c07c853d238ce37b7bc70 or later for your endeavours from now on.

Please report back if you are successful (or not).

**Comment by kippi6171** [comment]
That version is exiting with:

Last 5 lines of Snoopy installation log file:
### with an argument to avoid this error message:
###
###     ./bootstrap.sh geezer-os
###

**Comment by bostjan** [comment]
You will need to edit install script and add "geezer-os" argument to ./bootstrap.sh invocation, around line 160.

b.
