### ISSUE TITLE
echo as sudo

### ISSUE THREAD

**Issue by kippi6171** [a2o/snoopy#99]
All

All for some reason if I do:

echo "test" >/tmp/test

This isn't logged by snoopy, everything else is logged, but our worry is someone will echo "" to a file.

Thanks

Chris

**Comment by bostjan** [comment]
Command "echo" without specifying path is using bash built-in, and thus not executing command, thus Snoopy can not detect and log it. /bin/echo > /tmp/test will be logged, but only up to the ">" character.

b.

**Comment by kippi6171** [comment]
ah great, makes perfect sense now.
